import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [joda-time website](https://www.joda.org/joda-time/) */
    const val joda_time: String = "joda-time:joda-time:" + Versions.joda_time

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    const val ncm_gradle_publish_gradle_plugin: String =
            "ncm.gradle.publish:ncm.gradle.publish.gradle.plugin:" + Versions.ncm_gradle_publish_gradle_plugin

    const val ncm_gradle_repos_gradle_plugin: String =
            "ncm.gradle.repos:ncm.gradle.repos.gradle.plugin:" + Versions.ncm_gradle_repos_gradle_plugin

    const val ncm_gradle_version_gradle_plugin: String =
            "ncm.gradle.version:ncm.gradle.version.gradle.plugin:" + Versions.ncm_gradle_version_gradle_plugin

    /**
     * [hamcrest-integration website](https://github.com/hamcrest/JavaHamcrest) */
    const val hamcrest_integration: String =
            "org.hamcrest:hamcrest-integration:" + Versions.hamcrest_integration
}
